services:
  shawn-api:
    image: ghcr.io/shawnphoffman/shawn-api:latest
    container_name: shawn-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3005:3000"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=shawn"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  watchtower-api:
    image: containrrr/watchtower:latest
    container_name: watchtower-api
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 300 --label-enable --scope shawn

